language: node_js
node_js:
- '8'
dist: trusty
services:
- mongodb
- redis-server
env:
  global:
  - PORT=3000
  - MONGO_URI=mongodb://127.0.0.1:27017/node-adv
  - REDIS_URL=redis://127.0.0.1:6379
  - GOOGLE_CLIENT_ID=416532810158-7fa86pqgiat2cbi6pso141q5mq1l4r80.apps.googleusercontent.com
  - secure: ctwklBf3mVAuN3pXZIBgzSebMlvcTxCBSk4LfjiZO1jkf04C6Zl/71cffpntJLdl35wZ7OJcexAgxlyl2q43v9jgCjJQyhJ85c2XJYguScPxt7ob62S470egxSh4+XnFTXijJ65IcfrsIODJvEcwYyuL/KzXXg2457BT9cSyqLnTl1ZeiwXRCx1tyh4mxnp7SfNC25LxKntxaOSq99oAWN9reefE5Ncw7Qw4t0xejkaNU+GcAuVVuwsYxfkuemuTOakTVRs5hMu0mSeSfJbkMRZHlEnicCrilKVa+LvXe9Nx3ofVTKNWrKcBlLUSkRelj91bp7mWqVaPGYpweeIyqgiIeKkwnf9IUmn28Fa735M9ZDrKtVDOoH5tk5yMFtlYeYR1osiMWYxpfhO8YM34s5QHgQQCGfG8iaEa6cIDrRSIvHbWrFJ2E1ma6hZfYiO1Qi4jTQTfPfa1EUHJxjC/yD4iWEltEDsANMJLZKVNdqO9pXIRxKg/n94fQDO0S0zG/jlZ4x0h6v88nPvejGIeBcRUm4hgMrqzILkxO1Y5gRObfqAg83nwHGGy8M5YyOg0gROY1fTcrZmodR3+vmUIhGjaLVDoTVzkuNnlxdmNhbwL8YzEuXP6BzaK8IFyIzh5vi3uQlh+jOrLK5TCgUntcUiPInI8Zscrg7ABkeWOmNs=
  - secure: DmM5nhgkC3up2d8X4/rre6BKmoLbHQSiPMPx3xTNyoHpcGHWZ7OzSRluj0oCF9G1/VNI1VacXvzsfs1qBWApFRLopaNQjWZGnPOK+rl7h6xNQX2BkUKPX8icmg8xGMzrEPYvtJcI0shnHjMT06pFz53yf+ANa9nJZgJmhYi3IICLnuasz0+gvb0d1puU/VJEVObv2LaFt8NAM6HBKpmBrE6550ALV8N9FKODpTZYDn4XwloNhYys4eNHRT8fLxf0rZN4+xy0qfFTV6coWdDxrID+/BZ1dWM+ezgHbi4lO1cTnztH6C2Hi46Ic0pRVEAKEK82dm24zUvZT5hy0jHFQW9xn5NMCc8gxaNChDYu6Ccn9W/rSvDuwWftB3wCDZnyQxhKUG/QK3Pf8vbJ4Xf9fPGGA0rFZX4CvuatYrngEee5svWbtByXls9Bb2IAiK58/sx9JpQxHu4SivWAPYFVr1OJo4uji1OKt8TfXOV/wflxFgscYQ37Xv27Pi2/i9GUkXs6+kqCmmMB3Odv/BYvNgoRgnvVPZcBdTw8Z0vTHoqC/8Jz0TlKkLE9JENakizjS2Wx4vBYzSryb0CSmcmCXrnBopEfCQG4h5aCdLmFR5aXmpLhjgPWRwNfnAIGChUwJADiVinnvNCS+VdnLqjqhbgzFQLIuCpdnu0YTFNUNHM=
  matrix:
  - NODE_ENV=ci
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
- npm run build
script:
- nohup npm run start &
- sleep 3
- npm run test
